services:
- docker

script:
- docker build --target test --tag todo-app:test .
- docker run -p 5000:5000 --env-file ./.env.test todo-app:test tests
- docker build --target production --tag todo-app:prod .
- docker run -d -p 5000:5000 -e TRELLO_BOARD_ID -e TRELLO_KEY -e TRELLO_TOKEN -e ID_ORGANIZATION todo-app:prod