version: "3.9"
services:
  todo-app:
    build: 
        context: .
        dockerfile: Dockerfile
        target: development
    image: todo-app:dev
    ports: 
        - "5000:5000"
    env_file: ./.env
    volumes: 
        - ./todo_app:/app/todo_app