version: "3.9"
services:
  todo-app:
    build: 
        context: .
        dockerfile: Dockerfile
        target: production
    image: todo-app:prod
    ports: 
        - "5000:5000"
    env_file: ./.env